[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
farms = "3tC6fGzkF5xpK1paLMvcGQV2WpY2QEYzdMPSGAogbjzg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
